- hosts: localhost
  connection: local
  vars:
    resource_group: testaimle
    webapp_name: myWebApp
    plan_name: myAppServicePlan
    location: eastus
  tasks:
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: testaimle
        location: eastus

    - name: Create App Service on Linux with Java Runtime
      azure_rm_webapp:
        resource_group: testaimle
        name: myWebApp
        plan:
          resource_group: testaimle
          name: myAppServicePlan
          is_linux: true
          sku: S1
          number_of_workers: 1
        frameworks:
          - name: "java"
            version: "8"
            settings:
              java_container: tomcat
              java_container_version: 8.5
